
project_id = "gqgtoswadkblloyifklq"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 5432
shadow_port = 5433
major_version = 15

[studio]
port = 3000

[inbucket]
port = 4003

[storage]
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://preview--link-shop-showcase.lovable.app", "https://link-shop-showcase.lovable.app", "https://b180e0c0-d2e2-4215-88aa-4b49c2ecd66e.lovableproject.com"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_confirmations = false

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true
