// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqgtoswadkblloyifklq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxZ3Rvc3dhZGtibGxveWlma2xxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NDU0NjEsImV4cCI6MjA2MTAyMTQ2MX0.ZVzlQ62bFB1vPBSqtGdc_89tVNn9S4erLqhAjnfp4P8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);